# Generated by Django 3.0.4 on 2020-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=50)),
                ('hAddress', models.CharField(max_length=50)),
                ('hClass', models.CharField(max_length=10)),
                ('hType', models.CharField(default='', max_length=10)),
                ('hPing', models.PositiveIntegerField(default='')),
                ('hFloor', models.PositiveIntegerField(default='')),
                ('hFloorAll', models.PositiveIntegerField(default='')),
                ('hEle', models.BooleanField(default=True)),
                ('hMoney', models.PositiveIntegerField(default='')),
                ('hAge', models.PositiveIntegerField(default='')),
                ('hPic', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='old_distribute_sm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTY_ID', models.PositiveIntegerField()),
                ('COUNTY', models.CharField(max_length=5)),
                ('TOWN_ID', models.PositiveIntegerField()),
                ('TOWN', models.CharField(max_length=5)),
                ('FLD01', models.PositiveIntegerField()),
                ('FLD02', models.FloatField()),
                ('FLD03', models.PositiveIntegerField()),
                ('FLD04', models.PositiveIntegerField()),
                ('FLD05', models.PositiveIntegerField()),
                ('FLD06', models.PositiveIntegerField()),
                ('INFO_TIME', models.CharField(max_length=5)),
            ],
        ),
    ]
