# Generated by Django 3.0.4 on 2020-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=50)),
                ('hAddress', models.CharField(max_length=50)),
                ('hClass', models.CharField(max_length=10)),
                ('hType', models.CharField(default='', max_length=10)),
                ('hPing', models.PositiveIntegerField(default='')),
                ('hFloor', models.PositiveIntegerField(default='')),
                ('hFloorAll', models.PositiveIntegerField(default='')),
                ('hEle', models.BooleanField(default=True)),
                ('hMoney', models.PositiveIntegerField(default='')),
                ('hAge', models.PositiveIntegerField(default='')),
            ],
        ),
    ]
