# Generated by Django 3.0.5 on 2020-04-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='old_distribute_sm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTY_ID', models.PositiveIntegerField()),
                ('COUNTY', models.CharField(max_length=5)),
                ('TOWN_ID', models.PositiveIntegerField()),
                ('TOWN', models.CharField(max_length=5)),
                ('FLD01', models.PositiveIntegerField()),
                ('FLD02', models.FloatField()),
                ('FLD03', models.PositiveIntegerField()),
                ('FLD04', models.PositiveIntegerField()),
                ('FLD05', models.PositiveIntegerField()),
                ('FLD06', models.PositiveIntegerField()),
                ('INFO_TIME', models.CharField(max_length=5)),
            ],
        ),
    ]
