# Generated by Django 3.0.4 on 2020-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='hPic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
